version: "3.8"

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: defaultpassword
    expose:
      - "5432"
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  geant4-rest-api:
    image: lobis/geant4-rest-api:latest
    environment:
      POSTGRES_HOST: database
      POSTGRES_PASSWORD: defaultpassword
      POSTGRES_MAX_BATCH_INSERTS: 50000
    expose:
      - "9080"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  webservice:
    image: lobis/interactive-simulation:latest
    environment:
      POSTGRES_HOST: database
      POSTGRES_PASSWORD: defaultpassword
      SIMULATION_HOST: geant4-rest-api
    expose:
      - "8080"
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
